name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  shelf_plus: ^1.5.0
  shared: 
    path: ../shared
  http: ^0.13.5
  shelf_cors_headers: ^0.1.4
  openid_client: ^0.4.6
